runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /.*
  script: main.app
  http_headers:
    Access-Control-Allow-Origin: '*'
    
env_variables:
  MODEL_NAME: 'pb_model_041919'

